
task:
  matrix:
    - name: FreeBSD 12.4
      freebsd_instance:
        image: freebsd-12-4-release-amd64
    - name: FreeBSD 13.1
      freebsd_instance:
        image: freebsd-13-1-release-amd64
    - name: FreeBSD 13.2
      freebsd_instance:
        image: freebsd-13-2-release-amd64
  install_script:
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
    - pkg update -f
    - pkg upgrade -y
    - pkg install -y git gmake pkgconf e2fsprogs-libuuid sqlite3 gtkmm30 cppzmq libgit2 glm opencascade podofo09 libarchive meson cmake
  script:
    - ls
    - clang --version
    - mkdir ../build
    - meson setup ../build --cmake-prefix-path=/usr/local/lib
    - meson compile -C ../build

