FROM debian:bookworm-slim AS build
COPY src /src
RUN apt-get update
RUN apt-get upgrade
RUN apt-get install -y build-essential libsqlite3-dev util-linux librsvg2-dev libcairomm-1.0-dev libepoxy-dev libgtkmm-3.0-dev uuid-dev libzmq5 libzmq3-dev libglm-dev libgit2-dev libcurl4-gnutls-dev liboce-ocaf-dev libpodofo-dev python3-dev libarchive-dev git python3-cairo-dev libosmesa6-dev
WORKDIR /src
RUN meson setup build --buildtype release
RUN meson compile -C build horizon.so
RUN strip build/horizon.so

FROM debian:bookworm-slim
RUN apt-get update && apt-get upgrade  -y
RUN apt-get install -y --no-install-recommends python3 libarchive13 libpython3.7 libglibmm-2.4-1v5 libpodofo0.9.6 liboce-ocaf11 python3-pygit2 git ca-certificates  python3-cairo libosmesa6 libcairomm-1.0-1v5
COPY --from=build /src/build/horizon.so /usr/local/lib/python3.11/dist-packages
