FROM debian:bookworm-slim AS build
RUN apt-get update && apt-get install -y --no-install-recommends python3 libarchive13 libglibmm-2.4-1v5 liboce-ocaf11 git ca-certificates libosmesa6 libcairomm-1.0-1v5 libgit2-1.5
RUN apt-get install -y build-essential libsqlite3-dev util-linux librsvg2-dev libcairomm-1.0-dev libepoxy-dev libgtkmm-3.0-dev uuid-dev libzmq5 libzmq3-dev libglm-dev libgit2-dev libcurl4-gnutls-dev liboce-ocaf-dev libpodofo-dev libarchive-dev git libosmesa6-dev meson cmake
COPY src /src
WORKDIR /src
RUN meson setup build --buildtype release
RUN meson compile -C build horizon-pr-review
RUN strip build/horizon-pr-review

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends python3 libarchive13 libglibmm-2.4-1v5 liboce-ocaf11 git ca-certificates libosmesa6 libcairomm-1.0-1v5 libgit2-1.5
COPY --from=build /src/build/horizon-pr-review /usr/local/bin

ENTRYPOINT ["/usr/local/bin/horizon-pr-review"]
CMD ["--help"]
