FROM debian:bullseye AS build
RUN apt-get update && apt-get install -y --no-install-recommends python3 libzip4 libglibmm-2.4-1v5 liboce-ocaf11 git ca-certificates libosmesa6 libcairomm-1.0-1v5 libgit2-28
RUN apt-get install -y build-essential libsqlite3-dev util-linux librsvg2-dev libcairomm-1.0-dev libepoxy-dev libgtkmm-3.0-dev uuid-dev libboost-dev  libzmq5 libzmq3-dev libglm-dev libgit2-dev libcurl4-gnutls-dev liboce-ocaf-dev libpodofo-dev libzip-dev git libosmesa6-dev
COPY src /src
WORKDIR /src
RUN make -j$(nproc) build/horizon-pr-review
RUN strip build/horizon-pr-review

FROM debian:bullseye
RUN apt-get update && apt-get install -y --no-install-recommends python3 libzip4 libglibmm-2.4-1v5 liboce-ocaf11 git ca-certificates libosmesa6 libcairomm-1.0-1v5 libgit2-28
COPY --from=build /src/build/horizon-pr-review /usr/local/bin

ENTRYPOINT ["/usr/local/bin/horizon-pr-review"]
CMD ["--help"]
